require 'ripper'
require 'parser/current'
require 'colorize'

require_relative '../lib/inspectors/base'
require_relative '../lib/inspectors/method_length'
require_relative '../lib/inspectors/indentation_helper'
require_relative '../lib/inspectors/indentation'
require_relative '../lib/inspectors/naming'
require_relative '../lib/helpers/start_inspect'
require_relative '../lib/helpers/token_handler'
require_relative '../lib/helpers/file_handler'
require_relative '../lib/inspectors/maximum_line_length'
require_relative '../lib/inspectors/trailing_white_spaces'
require_relative '../lib/inspectors/space_around_op'
require_relative '../lib/helpers/parser'
require_relative '../lib/helpers/start_inspect_parser'
